# put common definitions in here
CC  = g++
CPPFLAGS = -g -std=gnu++0x
LD  = g++
LDFLAGS =
AR  = ar
ARFLAGS = rvc
RANLIB  = ranlib
RM  = rm
ECHO  = echo
BUILD = build
BIN = bin
LIBDIR = lib

SHELL = /bin/sh

.SILENT :
